# Generated by Django 4.0.2 on 2022-02-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterfood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(max_length=200)),
                ('filters', models.CharField(max_length=200)),
                ('foods', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
